"""empty message

Revision ID: 73ab5b023bd7
Revises: a72776c9ee39
Create Date: 2022-02-21 11:19:35.780425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ab5b023bd7'
down_revision = 'a72776c9ee39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
