"""empty message

Revision ID: d24e2982ce92
Revises: bd00b4f78720
Create Date: 2022-02-21 18:30:32.782080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24e2982ce92'
down_revision = 'bd00b4f78720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body')
    # ### end Alembic commands ###
