"""empty message

Revision ID: 633241c0584f
Revises: 73ab5b023bd7
Create Date: 2022-02-21 11:20:00.038187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633241c0584f'
down_revision = '73ab5b023bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###
