"""empty message

Revision ID: f5bf59c5cbc6
Revises: 88da550eb640
Create Date: 2022-02-15 17:09:42.292562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5bf59c5cbc6'
down_revision = '88da550eb640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comments', 'postId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'postId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comments', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
